# LAB | Intro to Machine Learning

**Load the data**

In this challenge, we will be working with Spaceship Titanic data. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [1]:
#import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [3]:
print(spaceship.columns)
display(spaceship.info)

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

<bound method DataFrame.info of      PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
...          ...        ...       ...       ...            ...   ...    ...
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines
...           ...        ...           ...     ...     ...                ...
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre

      Transported
0           False
1            True
2           False
3           False
4            True
...           ...
8688        False
8689        False
8690         True
8691        False
8692         True

[8693 rows x 14 columns]>

**Check for data types**

In [4]:
print(spaceship.dtypes)

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [5]:
display(spaceship.isnull())
print(spaceship.isnull().sum())

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8689,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8690,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8691,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8692,False,False,False,False,False,False,False,False,False,False,False,False,False,False

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [6]:
spaceship_clean = spaceship.dropna()
spaceship_clean.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**KNN**

K Nearest Neighbors is a distance based algorithm, and requeries all **input data to be numerical.**

Let's only select numerical columns as our features.

In [ ]:
"""spaceship_f = pd.DataFrame(spaceship_clean["data"], columns= spaceship_clean["feature_names"] )
spaceship_f["Transported"] = spaceship_clean["target"]"""

In [12]:
features = spaceship_clean.drop(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'VIP', 'Name', 'Transported'], axis=1)
features.head()

    Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
0  39.0          0.0        0.0           0.0     0.0     0.0
1  24.0        109.0        9.0          25.0   549.0    44.0
2  58.0         43.0     3576.0           0.0  6715.0    49.0
3  33.0          0.0     1283.0         371.0  3329.0   193.0
4  16.0        303.0       70.0         151.0   565.0     2.0

And also lets define our target.

In [13]:
target = spaceship_clean['Transported'] 
target.head()

0    False
1     True
2    False
3    False
4     True
Name: Transported, dtype: bool

**Train Test Split**

Now that we have split the data into **features** and **target** variables and imported the **train_test_split** function, split X and y into X_train, X_test, y_train, and y_test. 80% of the data should be in the training set and 20% in the test set.

In [14]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size = 0.20, random_state=0)

In [18]:
display(X_train.head())
display(X_test.head())
print(y_train.head())
print(y_test.head())

       Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
3432  32.0          0.0        0.0           0.0     0.0     0.0
7312   4.0          0.0        0.0           0.0     0.0     0.0
2042  30.0          0.0      236.0           0.0  1149.0     0.0
4999  17.0         13.0        0.0         565.0   367.0     1.0
5755  26.0          0.0        0.0           0.0     0.0     0.0

       Age  RoomService  FoodCourt  ShoppingMall     Spa  VRDeck
2453  50.0          0.0        0.0           0.0     0.0     0.0
1334  18.0          0.0        0.0           0.0     0.0     0.0
8272  15.0          0.0        0.0           0.0     0.0     0.0
5090  52.0          0.0        0.0           0.0     0.0     0.0
4357  62.0          0.0     1633.0           0.0  1742.0     0.0

3432    False
7312     True
2042    False
4999    False
5755     True
Name: Transported, dtype: bool
2453     True
1334    False
8272     True
5090    False
4357     True
Name: Transported, dtype: bool

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

You need to choose between **Classificator** or **Regressor**. Take into consideration target variable to decide.

Initialize a KNN instance without setting any hyperparameter.

In [19]:
from sklearn.neighbors import KNeighborsClassifier #KNeighboursRegressor if you have regression

In [20]:
knn = KNeighborsClassifier() # n_neighbors = K

Fit the model to your data.

In [21]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

Evaluate your model.

In [23]:
pred = knn.predict(X_test)
display(pred)

array([ True,  True,  True, ...,  True,  True,  True], shape=(1322,))

In [24]:
y_test.values

array([ True, False,  True, ...,  True,  True,  True], shape=(1322,))

In [25]:
print(f"The accuracy the model is {knn.score(X_test, y_test)*100: .2f}%")

The accuracy the model is  76.55%

In [26]:
# to check where the mistake is:
import numpy as np
np.where(pred != y_test.values)

(array([   1,    3,    4,    8,   14,   16,   25,   27,   32,   33,   40,
          45,   47,   56,   67,   68,   71,   72,   74,   76,   77,   81,
          84,   87,   88,   90,   93,   94,  110,  114,  122,  128,  142,
         145,  153,  155,  162,  164,  170,  171,  175,  177,  186,  190,
         202,  211,  216,  222,  225,  226,  228,  230,  235,  236,  238,
         251,  252,  259,  262,  263,  264,  265,  270,  271,  276,  287,
         293,  300,  320,  321,  323,  326,  328,  330,  336,  343,  347,
         352,  353,  364,  365,  368,  370,  372,  375,  377,  379,  380,
         382,  389,  396,  403,  405,  407,  414,  415,  416,  418,  419,
         427,  429,  436,  437,  438,  442,  443,  444,  449,  451,  452,
         454,  461,  465,  467,  472,  478,  495,  496,  503,  504,  505,
         511,  515,  522,  523,  531,  532,  544,  548,  552,  553,  555,
         557,  558,  563,  564,  569,  575,  576,  578,  580,  583,  594,
         601,  602,  609,  623,  624,  630,  631,  639,  642,  644,  646,
         651,  652,  657,  660,  661,  670,  671,  676,  677,  679,  681,
         684,  688,  700,  703,  706,  718,  719,  721,  724,  729,  736,
         743,  746,  751,  769,  772,  781,  791,  792,  794,  796,  797,
         798,  799,  803,  804,  808,  810,  812,  819,  821,  826,  830,
         837,  840,  850,  852,  856,  859,  863,  866,  867,  871,  874,
         892,  896,  897,  899,  904,  907,  910,  918,  921,  923,  930,
         936,  945,  946,  952,  953,  954,  961,  968,  973,  975,  977,
         984,  986,  988,  989,  993,  994,  997, 1000, 1006, 1013, 1014,
        1015, 1024, 1025, 1031, 1032, 1033, 1038, 1048, 1058, 1060, 1070,
        1077, 1088, 1090, 1095, 1096, 1102, 1104, 1105, 1114, 1115, 1116,
        1124, 1125, 1128, 1132, 1137, 1140, 1142, 1145, 1150, 1169, 1172,
        1174, 1175, 1176, 1178, 1187, 1191, 1193, 1204, 1209, 1221, 1224,
        1231, 1233, 1235, 1239, 1243, 1246, 1247, 1251, 1257, 1260, 1265,
        1275, 1277, 1281, 1282, 1283, 1295, 1297, 1298, 1301, 1306, 1311,
        1312, 1317]),)

**Congratulations, you have just developed your first Machine Learning model!**